### ISSUE TITLE
Is it possible to run in serverless environment?

### ISSUE THREAD

**Issue by dmoimpact** [femtopixel/docker-google-lighthouse#21]
**Description**

I am trying to run this docker container into a serverless environment on Google Cloud, using Cloud build. In the final step I want to export json file to a cloud bucket - I have tried several options. Latest I've tried copying the full folder in order to see if I could spot where the file gets exported. I do however get acess denied.

**Command line I used to start the container**
YALM SETUP:
```yaml
steps:
- name: 'femtopixel/google-lighthouse'
  dir: '/build/'
  args: ['https://www.google.dk/', '--output json', '--output-path', './google.json']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '.', 'gs://myBucket']

timeout: 1200s
```

**Describe the results you received:**
Error: EACCES: permission denied, open './google.json'
Runtime error encountered: EACCES: permission denied, open './google.json

**Describe the results you expected:**
Expected the file to be found on the next buildstep of my build so it can be exported.
